---
  - name: run letsencrypt ocsp script
    command: "/usr/local/bin/update_{{ domain }}_ocsp_stapling.sh 1>/dev/null"
    become: yes
    become_user: ocsp-updater
    changed_when: False
    failed_when: False
