---
  - name: Checkout dehydrated
    git:
      repo: "https://github.com/dehydrated-io/dehydrated.git"
      dest: "/opt/dehydrated"
      version: master
      force: yes

  - name: create /etc/letsencrypt hierarchy
    file:
      dest: /etc/{{ item }}
      owner: root
      group: ssl-cert
      state: directory
      mode: 0750
    with_items:
      - "letsencrypt/live/{{ domain }}"

  - name: generate dehydrated folders
    file:
      dest: /etc/{{ item }}
      state: directory
      mode: 0750
    with_items:
      - dehydrated/accounts
      - dehydrated/hook.d

  - name: generate dehydrated hook.sh
    template:
      dest: /etc/dehydrated/hook.sh
      src: dehydrated/hook.sh
      mode: 0775

  - name: generate dehydrated dns-01 private & key
    copy: dest=/etc/dehydrated/dns-01-key.{{ item }}
          content={{ lookup('keepass', 'ansible/ssl/dns-01/'+ansible_fqdn+'.attr_'+item) }}
          mode=0640 owner=root group=root
    with_items:
      - key
      - private
    when: use_dns

  - name: create well-known directory
    file:
      path: /var/www/dehydrated
      state: directory
      mode: 0775
    when: not use_dns

  - name: generate dehydrated config
    template:
      dest: /etc/dehydrated/config
      src: dehydrated/config
      mode: 0664

  - name: generate dehydrated account directory
    file: dest=/etc/dehydrated/accounts/{{ lookup('keepass', 'ansible/ssl/letsencrypt-account.username') }}
          state=directory
          owner=root group=root mode=0750

  - name: generate dehydrated account_key.pem
    copy: dest=/etc/dehydrated/accounts/{{ lookup('keepass', 'ansible/ssl/letsencrypt-account.username') }}/account_key.pem
          content={{ lookup('keepass', 'ansible/ssl/letsencrypt-account.attr_account_key') }}
          owner=root group=root mode=0640

  - name: generate dehydrated registration_info.json
    copy: dest=/etc/dehydrated/accounts/{{ lookup('keepass', 'ansible/ssl/letsencrypt-account.username') }}/registration_info.json
          content={{ lookup('keepass', 'ansible/ssl/letsencrypt-account.attr_registration_info') }}
          owner=root group=root mode=0640

  - name: ensure domain {{ domain }} is in domains.txt
    lineinfile:
      path: /etc/dehydrated/domains.txt
      state: present
      regexp: '^{{ domain }}$'
      line: '{{ domain }}'
      create: yes
      mode: 0644

  - name: generate or renew certificate (takes some time)
    shell: "/opt/dehydrated/dehydrated --cron"
    changed_when: false

  - name: deploy dehydrated systemd units
    copy:
      dest: /etc/systemd/system/
      src: "dehydrated/{{ item }}"
      mode: 0644
    loop:
      - dehydrated.service
      - dehydrated.timer
    register: dehydrated_units

  - name: enable dehydrated systemd timer
    systemd:
      name: dehydrated.timer
      daemon_reload: yes
      enabled: yes
      state: started
    when: dehydrated_units.changed
