---
  - include: letsencrypt.yml
    when: letsencrypt_fake is not defined

  - include: letsencrypt_fake.yml
    when: letsencrypt_fake is defined

  - include: ocsp.yml

  - include: monitoring.yml
    tags:
      - monitoring
      - check_system
