---
- group: name=ftp

- user: state=present
        name="ftp"
        groups="ftp"
        create_home="no"
        shell="/bin/false"

- file: path=/srv/ftp state=directory
        mode=0755 owner=cdn-app group=root
