---
  - import_tasks: packages.yml
    tags:
      - mirrorbits
      - rsync

  - import_tasks: rsync-server.yml
    tags: rsync

  - import_tasks: mirrorbits.yml
    tags: mirrorbits

  - import_tasks: mirrorbits-api.yml
    tags: mirrorbits

  - import_tasks: uploaders.yml
    tags: uploaders

  - import_tasks: cdn-app.yml
    tags: cdn-app

  - import_tasks: static.yml
    tags: static

  - import_tasks: nginx.yml
    tags:
      - nginx
