---
  - import_tasks: packages.yml
    tags:
      - mirrorbits
      - rsync

  - import_tasks: rsync-server.yml
    tags: rsync

  - import_tasks: mirrorbits.yml
    tags: mirrorbits

  - import_tasks: mirrorbits-api.yml
    tags: mirrorbits

  - import_tasks: uploaders.yml
    tags: uploaders

  - import_tasks: static.yml
    tags: static

  - import_tasks: nginx.yml
    tags:
      - nginx

  - import_tasks: ../../media-mirror/tasks/nginx-cdn-node.yml
    when: cdn_node is defined

  - import_tasks: ../../media-mirror/tasks/vsftpd.yml
    when: cdn_node is defined
