---
 - include: packages.yml
   tags: packages
 - include: undeploy.yml

 # - include: artwork.yml
 #   tags: artwork
 #   with_items: "{{ transcoder_streams }}"
 #   when: transcoder_streams is defined
 #   loop_control:
 #     loop_var: transcoder_stream

 - include: cleanup.yml
   tags: cleanup

 - include: stream-api.yml
   tags: stream-api
