---
  # Install package
  - name: install icecast streaming server
    apt:
      name: icecast2
      state: latest

  # Create directories
  - name: create dump file directory for icecast
    file:
      dest: /srv/icecastdumps
      state: directory
      owner: icecast2
      group: icecast
      mode: 0755
    when: icecast_push_master|bool

  # Configure
  - name: configure the icecast streaming server
    template:
      src: icecast.xml
      dest: /etc/icecast2/icecast.xml
      owner: icecast2
      group: icecast
      mode: 0660
    register: icecast_conf

  - name: create default icecast2 config
    template:
      src: icecast_default
      dest: /etc/default/icecast2
      mode: 0644
    register: icecast_default_conf

  - name: create custom override systemd unit for icecast
    template:
      src: icecast2.service
      dest: /etc/systemd/system/icecast2.service
      mode: 0644
    register: icecast_service

  - name: restart icecast2 service
    service:
      name: icecast2.service
      state: restarted
    when: icecast_conf.changed or icecast_default_conf.changed or icecast_service.changed

  # Start service
  - name: enable icecast2 on boot
    service:
      name: icecast2.service
      enabled: yes
      state: started
    when: icecast|bool

  # Stop service
  - name: disable icecast2 on boot
    service:
      name: icecast2.service
      enabled: no
      state: stopped
    when: not icecast|bool