# stream name RegExp
stream-match = '^[0-9a-zA-Z\-]+$'

# stream timeout in seconds
timeout = 3600

# transcoding sink
sink = "live.ber.c3voc.de:7999"

# artwork base directory
artwork_base = "http://live.ber.c3voc.de/artwork"


# stream backends to parse streams from
[[ backends ]]
type = "icecast"
address = "live.ber.c3voc.de:7999"

[[ backends ]]
type = "icecast"
address = "ingest.c3voc.de:8000"

[[ backends ]]
type = "srtrelay"
api = "ingest.c3voc.de:8084"
relay = "ingest.c3voc.de:1337"

# transcoders to assign streams to
#   host - transcoder hostname
#   capacity - max streams on that transcoder
#   allow - exclusively schedule those streams
[[ transcoders ]]
host = "tweety.lan.c3voc.de"
capacity = 4

[[ transcoders ]]
host = "blade1.lan.c3voc.de"
capacity = 3

#[[ transcoders ]]
#host = "blade2.lan.c3voc.de"
#capacity = 2
#
#[[ transcoders ]]
#host = "blade3.lan.c3voc.de"
#capacity = 2

[[ transcoders ]]
host = "loop-transcoder"
capacity = 1
allow = ["sloop"]

