---
  - include: ../../../register/bin_path.yml
    tags: bin_path
  - include: locale.yml
  - include: resolv.yml
    tags:
      - resolv
      - dns
  - include: apt_proxy.yml
  - include: repos.yml
    tags:
      - repos
      - apt
  - include: packages.yml
    tags: [packages]
  - include: kernel.yml
    when: "system.type == 'pc' and 'proxmox' not in group_names"
    tags: kernel
  - include: vim.yml
  - include: sudo.yml
  - include: grub.yml
    when: "system.type == 'pc' and 'proxmox' not in group_names"
  - include: ntp.yml
    when: ansible_virtualization_type is defined and ansible_virtualization_type != 'lxc'

  - include: acpi_undeploy.yml
    when: system.type == 'pc' and ansible_virtualization_role == 'guest'
    tags: acpi

  - include: acpi.yml
    when: system.type == 'pc' and ansible_virtualization_role != 'guest'
    tags: acpi

  - include: molly-guard.yml
  - include: ssh_known_hosts.yml
    when: "'proxmox' not in group_names"
  - include: ssl.yml
  - include: smart.yml
  # realise users
  - include: user.yml user={{ users }}
    tags: user
  - include: monitoring.yml
    tags:
      - monitoring
      - check_system




  - name: setting voc password
    user: name=voc
          password={{ user_voc_password }}
    tags: user

  # Modify message of the day
  - name: adding message of the day
    template: dest=/etc/motd
              src=motd/motd
              owner=root group=root mode=0644
