---
- name: Add rails user
  user:
    name: media
    shell: /bin/bash
    home: /srv/media
    state: present

# TODO install goaccess
- copy: src=goaccess.sh
        dest=/usr/local/bin
        owner=root group=root mode=0755

- import_tasks: packages.yml
  tags: media-app

- import_tasks: rails-app.yml
  tags: media-app

- import_tasks: nginx.yml
  tags:
    - nginx
