### Master-Relay variables
# - host stream-info api
# - do fanout
# - distribute local files via nginx
# - setup icedist for accepting streams
stream_master: no

# Generate relive snippets locally
relive_master: no

# fanout to youtube
youtube: no