---
# defaults vars for relay role

### Common variables
# use nginx
nginx: 'yes'

# use icecast
icecast: 'yes'

# firewalled from public access
hidden: no

### Master-Relay variables
# - host stream-info api
# - do fanout
# - distribute local files via nginx
# - setup icedist for accepting streams
stream_master: no

# Generate relive snippets locally
relive_master: no

# accept some external streams pushed to icecast
icecast_push_master: no

# fanout to youtube
youtube: no