---
  - apt:
      state: latest
      name:
        - rsync
        - vsftpd
  - import_tasks: cdn-sync.yml
  # TODO add rsyncd configuration
  #   mirrorbits checks via rsync, config is done in media-cdn role,
  #   extract to rsyncd server role someday
