---
  - name: install packages required to fanout streams
    apt:
      name:
        - python3-jinja2
      state: latest
      update_cache: yes
    tags: packages

  - name: create directories
    file: dest={{ item }} state=directory
          mode=0755 owner=root group=root
    with_items:
      - /opt/fanout/scripts/
      - "{{ relay_fanout.hls_write_path }}"
      - "{{ relay_fanout.dash_write_path }}"
      - "{{ relay_fanout.thumbnail_write_path }}"

  - name: copying fanout-scripts
    copy: dest=/opt/fanout/scripts/{{ item }}
          src=fanout/{{ item }}
          owner=root group=root mode=0755
    with_items:
      - audio.py
      - dash.py
      - hls.py
      - webm.py
      - thumbnail.py
      - youtube.py
      - fanout_utils.py

  - name: create fanout-update script
    copy:
      src: fanout/update_fanout.py
      dest: /opt/fanout/scripts/update_fanout.py
      mode: 0755
      owner: root
      group: root


  - name: create fanout systemd-units
    template: src=systemd-units/fanout_{{ item }}.service.j2
              dest="/etc/systemd/system/fanout_{{ item }}@.service"
              mode=0644 owner=root group=root
    with_items: ["hls", "dash", "webm", "audio", "thumbnail"]

  - name: create youtube systemd-units
    template: src=systemd-units/fanout_{{ item }}.service.j2
              dest="/etc/systemd/system/fanout_{{ item }}@.service"
              mode=0644 owner=root group=root
    with_items: ["youtube"]
    when: youtube is defined and youtube

  - name: create fanout systemd-target
    template: src=systemd-units/fanout.target.j2
              dest="/etc/systemd/system/fanout@.target"
              mode=0644 owner=root group=root

  - name: create fanout update service and timer
    template:
      src: "systemd-units/update_fanout.{{ item }}.j2"
      dest: "/etc/systemd/system/update_fanout.{{ item }}"
      mode: 0644
      owner: root
      group: root
    with_items:
      - service
      - timer

  - name: enable fanout update timer
    systemd:
      name: update_fanout.timer
      state: started
      enabled: yes
      daemon_reload: yes
    changed_when: false