---
  - include: ../../../register/bin_path.yml

  - include: upload.yml
    tags: [nginx, upload, stream_master]
    when: stream_master|bool

  - include: nginx.yml
    tags: [nginx, nginx-vhost]

  - include: iptables.yml
    tags: [firewall, iptables, nftables]

#  - include: sysctl.yml
#    tags: sysctl

  - include: collectd.yml
    tags: [collectd, monitoring]

  - include: relive.yml
    when: relive_master|bool
    tags: relive

  - include: fanout.yml
    when: stream_master|bool
    tags: fanout

  - include: upload-server.yml
    when: stream_master|bool
    tags: upload-server

  - include: register_relay.yml
    tags: register_relay
