---
  - include: ../../../register/bin_path.yml

  - include: nginx.yml
    tags: nginx
  - include: icecast.yml
    tags: icecast
  - include: iptables.yml
    tags: iptables
  - include: sysctl.yml
    tags: sysctl

  - include: relive.yml
    when: relive_master|bool
    tags: relive

  - include: icedist.yml
    when: stream_master|bool
    tags: icedist

  - include: fanout.yml
    when: stream_master|bool
    tags: fanout

  - include: stream_master.yml
    when: stream_master|bool
    tags: stream_api

  - include: register_relay.yml
    tags: register_relay
