---
  - include: ../../../register/bin_path.yml
  - include: undeploy.yml

  - include: nginx.yml
    tags: nginx
  - include: icecast.yml
    tags: icecast
  - include: iptables.yml
    tags: iptables
  - include: sysctl.yml
    tags: sysctl

  - include: relive.yml
    when: nginx_master is defined and nginx_master == 'yes'
    tags: relive

  - include: icedist.yml
    when: icedist is defined and icedist == 'yes'
    tags: icedist

  - include: fanout.yml
    when: fanout_streams is defined
    tags: fanout

  - include: rtmp_ingest.yml
    when: rtmp_ingest_streams is defined
    tags: rtmp_ingest

  - include: register_relay.yml
    tags: register_relay
