---
  - name: make sure ruby is installed
    apt: name=ruby state=latest

  - name: install register_relay client
    template: dest=/usr/local/sbin/register_relay
              src=register_relay/client.rb
              mode=0750 owner=root group=root
    notify: trigger register_relay

  - name: add register_relay systemd unit
    template:
      src: register_relay/register_relay.service.j2
      dest: /etc/systemd/system/register_relay.service
    notify: trigger register_relay

  - name: ensure relay register service is enabled
    systemd:
      name: register_relay
      daemon_reload: yes
      enabled: yes

  - name: install register bandwith measure client
    template: dest=/usr/local/sbin/register_bw_measure
              src=measure_bw/client.rb
              mode=0750 owner=root group=root
