---
  # Create needed directories
  - name: added nginx htdocs and caching directories
    file: "dest=/srv/nginx/{{ item }}
          owner=www-data group=www-data
          state=directory"
    with_items:
      - "cache/streaming_fcgi/"
      - "cache/tmp"
    tags:
      - install

  # Manage vhost
  - name: create vhost
    template: dest="/etc/nginx/sites-enabled/{{ item }}.conf"
              src="nginx/vhosts/{{ item }}.conf.j2"
              mode=0640 owner=root group=root
    with_items:
      - streaming.media.ccc.de
    notify:
      - reload nginx
    tags:
      - config
      - install

  - name: remove vhost
    file: dest="/etc/nginx/sites-available/{{ item }}.conf"
          state=absent
    with_items:
      - faq.c3voc.de
      - pre.streaming.media.ccc.de
    notify:
      - reload nginx
    tags:
      - config
      - install