# api-address = "172.17.0.1:8080"
[http]
# List of RTMP apps
applications = ["stream", "relay"]

# Prefix
prefix = "/backend"

# Allow insecure
#insecure = false

[store]
backend = "consul"

[store.file]
# Configure file storage path relative to working directory
#path = "store.db"