- synchronize:
    mode: pull
    src: /srv/www/media.ccc.de/media/
    dest: /srv/www/media.ccc.de/media/
  delegate_to: "{{ item }}"
  loop: "{{ groups['media-cdn'] }}"
  no_log: false
  tags: ['images']
