---
- include: nginx.yml
  tags: nginx
  when: "'relays' not in group_names"

- include: srtrelay.yml
  tags: srtrelay
  when: "'relays' not in group_names"

- include: rtmp-auth.yml
  tags: rtmp-auth
  when: "'relays' not in group_names"

- include: stream-api.yml
  tags: stream-api
