---
  - include: nginx_rtmp.yml
    tags: [nginx, rtmp]

  - include: rtmp_auth.yml
    when: rtmp is defined and rtmp|bool and rtmp_auth is defined and rtmp_auth|bool
    tags: [nginx, rtmp]

  - include: nginx.yml
    tags: [nginx]