---
- name: create nginx-rtmp config directory
  file:
    path: /etc/nginx-rtmp
    state: directory

- name: create nginx-rtmp config
  template:
    dest: /etc/nginx-rtmp/nginx.conf
    src: nginx-rtmp.conf.j2
    mode: 0640
    owner: root
    group: root
  notify:
    - restart nginx-rtmp

- name: install nginx-rtmp service
  copy:
    src: nginx-rtmp.service
    dest: /etc/systemd/system/nginx-rtmp.service
  notify: restart nginx-rtmp

- name: enable nginx-rtmp service
  systemd:
    name: nginx-rtmp
    state: started
    enabled: yes
    daemon_reload: yes

