---
  # Install packages
  - name: install nginx package
    apt: name=nginx state=latest
    tags: install

  # Configure
  - name: configure nginx
    template: dest=/etc/nginx/nginx.conf
              src=nginx.conf.j2
              mode=0640 owner=root group=root
    notify:
      - reload nginx
    tags:
      - config
      - install

  # Manage vhost
  - name: remove default vhost
    file: dest=/etc/nginx/sites-enabled/default state=absent
    notify: reload nginx

  # Enable/Disable service
  - name: enable/start nginx
    service: name=nginx enabled=yes state=started
    when: (nginx is defined and nginx|bool)

  - name: disable/stop nginx
    service: name=nginx enabled=no state=stopped
    when: not (nginx is defined and nginx|bool)

  # Certbot hooks/reloads
  - name: Check whether letsencrypt hookdir exists
    stat:
      path: /etc/letsencrypt/renewal-hooks/post/
    register: letsencrypt_hookdir

  - name: setup certbot-hook to reload nginx when the cert changes
    template: src=certbot-renewal-hook.sh.j2
              dest=/etc/letsencrypt/renewal-hooks/post/20-nginx
              mode=0755 owner=root group=root
    when: letsencrypt_hookdir.stat.exists

  - name: run certbot-hook once to reload nginx with possibly new cert changes
    shell: /etc/letsencrypt/renewal-hooks/post/20-nginx
    when: letsencrypt_hookdir.stat.exists
    changed_when: false

  # Cron job to reload nginx after ocsp update
  # TODO: Is there a better solution available?
  - name: reload nginx every morning for ocsp updates
    cron: name="reload nginx for ocsp update" hour=5 minute=5
          job="systemctl reload nginx" user=root
    when: letsencrypt_hookdir.stat.exists
    tags: install

  # Setup telegraf plugin
  - name: template nginx telegraf check
    template:
      src: telegraf_nginx.conf
      dest: /etc/telegraf/telegraf.d/nginx.conf
      mode: 0644
    register: telegraf_nginx
    tags: [monitoring, telegraf]

  - name: reload telegraf
    service:
      name: telegraf
      state: reloaded
    when: telegraf_nginx.changed
    tags: [monitoring, telegraf]