---
- name: remove nginx-rtmp config
  file:
    path: /etc/nginx-rtmp/nginx.conf
    state: absent

- name: stop and disable nginx-rtmp service
  systemd:
    name: nginx-rtmp
    state: stopped
    enabled: no
    daemon_reload: yes

- name: remove nginx-rtmp service
  file:
    path: /etc/systemd/system/nginx-rtmp.service
    state: absent

