---
  - hosts: monitoring
    roles:
      - { role: common, tags: ['common'] }
      - { role: letsencrypt, vars: { 'domain': '{{ ansible_fqdn }}'}, tags: ['letsencrypt'] }
      - { role: nginx, tags: ['nginx'] }
      - { role: monitoring-server, tags: ['monitoring'] }