---
  - hosts: relays
    roles:
      - { role: common, tags: ['common'] }
      - { role: monitoring-client, tags: ['monitoring'] }
      - { role: relay, tags: ['relay'] }
      - { role: ingest, tags: ['ingest'] } # stream-api only
