---
  - name: install monitoring packages
    apt:
      name:
        - nagios-plugins-basic
        - graphite-api
        - graphite-carbon
        - gunicorn3
        - grafana
      state: latest