---
  - name: template collectd-exporter.service
    template:
      src: systemd/collectd-exporter.service.j2
      dest: /etc/systemd/system/collectd-exporter.service
    register: collectd_exporter_service

  - name: enable/start collectd-exporter
    systemd:
      name: collectd-exporter
      enabled: yes
      state: restarted
      daemon-reload: yes
    when: collectd_exporter_service.changed

  - name: template prometheus configs
    template:
      src: prometheus/{{ item }}.j2
      dest: /etc/prometheus/{{ item }}
    with_items:
      - prometheus.yml
      - rules/recording.yml
    notify: reload prometheus
