---
  # Installation
  - name: install nginx package
    apt: name=nginx state=latest
    tags:
      - install

  # Create config
  - name: remove default vhost
    file: dest=/etc/nginx/sites-enabled/default state=absent

  - name: configure nginx
    template: dest=/etc/nginx/nginx.conf
              src=nginx/nginx.conf.j2
              mode=0644 owner=root group=root
              validate='nginx -t -c %s'
    notify:
      - reload nginx
    tags:
      - config
      - install

  # Manage vhost
  - name: "create {{ item }} vhost"
    template: dest="/etc/nginx/sites-available/{{ item }}"
              src="nginx/{{ item }}.j2"
              mode=0640 owner=root group=root
    with_items:
      - tracker.vhost.conf
      - default.vhost.conf
    notify:
      - reload nginx
    tags:
      - config
      - install

  - name: "enable {{ item }} vhost"
    file: src=/etc/nginx/sites-available/{{ item }}
          dest=/etc/nginx/sites-enabled/{{ item }}
          state=link
    notify:
      - reload nginx
    with_items:
      - tracker.vhost.conf
      - default.vhost.conf
    tags:
      - config
      - install

  # tracker fastcgi_params
  - name: create tracker spcific fastcgi_params
    template: dest="/etc/nginx/fastcgi_params"
              src="nginx/fastcgi_params"
              mode=0640 owner=root group=root
    notify:
      - reload nginx
    tags:
      - config
      - install

  - name: start nginx
    service: name=nginx enabled=yes state=started
    when: nginx is defined and nginx|bool
